// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8lzuoD7KVDfLfpeaK-3Ujm5Lf5OB69V0',
    appId: '1:384671783949:web:5852b9f824e5a6152f4944',
    messagingSenderId: '384671783949',
    projectId: 'fir-authnew-9b4e9',
    authDomain: 'fir-authnew-9b4e9.firebaseapp.com',
    storageBucket: 'fir-authnew-9b4e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKEQo8FFqwJlxJqohK4rjlqQ2lcuxOVTI',
    appId: '1:384671783949:android:bb888c5b69bb994e2f4944',
    messagingSenderId: '384671783949',
    projectId: 'fir-authnew-9b4e9',
    storageBucket: 'fir-authnew-9b4e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR9nYaHCx7hAepj6SGJJh0EDMuAgPmiOo',
    appId: '1:384671783949:ios:7266ba1f13af66032f4944',
    messagingSenderId: '384671783949',
    projectId: 'fir-authnew-9b4e9',
    storageBucket: 'fir-authnew-9b4e9.appspot.com',
    iosClientId: '384671783949-8ijdp8vo755oqhccsvctfjfaug8l8k3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR9nYaHCx7hAepj6SGJJh0EDMuAgPmiOo',
    appId: '1:384671783949:ios:7266ba1f13af66032f4944',
    messagingSenderId: '384671783949',
    projectId: 'fir-authnew-9b4e9',
    storageBucket: 'fir-authnew-9b4e9.appspot.com',
    iosClientId: '384671783949-8ijdp8vo755oqhccsvctfjfaug8l8k3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthNew',
  );
}
